In [1]:
%load_ext autoreload
%autoreload 2

%load_ext watermark
%watermark -a "Johann" -v -n -p numpy,scipy,sklearn,pandas

Johann Thu Oct 08 2020

CPython 3.8.5
IPython 7.18.1

numpy 1.19.2
scipy 1.5.2
sklearn 0.23.2
pandas 1.1.0

In [2]:
import os
import time
import pandas as pd
from pathlib import Path
from pyprojroot import here

data_path = Path(here('./data/raw'))

In [3]:
police_initiative = pd.read_csv(data_path / 'police_initiative.csv')

print(police_initiative.info())
police_initiative.head()

/Users/johann/miniconda3/envs/HRF/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,27,28,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,55,57,60,61,62,63,65,66,67,68,69,70,71,72,73,74,75,76,79,85,86,87,88,92,93,96,97,98,103,109,110,111,115,116,117,119,120,121,122,124,125,126,127,128,131,133,135,136,137,138,139,142,143,145,146,147,149,150,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,182,183,186,189,190,191,192,194,195,196,197,198,199,200,201,202,203,204,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,226,227,229,231,232,234,235,236,237,238,239,240,241,242,243,246,249,250,251,252,253,254,256,257,258,259,260,261,262,263,264,265,268,269,270,271,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,424,433,434,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94464 entries, 0 to 94463
Columns: 457 entries, Unnamed: 0 to Call_in_Response_To
dtypes: float64(85), int64(2), object(370)
memory usage: 329.4+ MB
None

,Unnamed: 0,Unnamed: 0.1,Incident Number,Incident Date Time,Incident Location,Officers Involved,Officers Race,Officers Ethnicity,Officers Sex,Officer Battered,...,Unnamed: 21,Blocked_Location_of_Incident,City_1,Type_of_Resistance,Response,Force_Caused_Injury,Off_Injured,Call_Dispatched_via_911,Call_was_Self_Initiated,Call_in_Response_To
0,0,0,2018-00079161,02/25/2018 10:23:00 PM,26TH / 15 LAWSONA BLV,1.0,W,NH,M,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,2013-00544482,12/29/2013 11:02:00 PM,NaN,1.0,B,NH,M,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,2018-00478744,12/14/2018 08:17:00 AM,9200 Block of AIRPORT BV,1.0,W,NH,M,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,2017-00316840,08/14/2017 01:50:00 AM,EW WBO / LONG ST,3.0,W;W;W,NH;NH;NH,M;M;M,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,IncidentNumber,NaN,IncidentLocation,NaN,OfficersRace,OfficersEthnicity,OfficersSex,OfficerBattered,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print(police_initiative.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94464 entries, 0 to 94463
Columns: 457 entries, Unnamed: 0 to Call_in_Response_To
dtypes: float64(85), int64(2), object(370)
memory usage: 329.4+ MB
None